### ISSUE TITLE
Computer-grafik 1 im WS2015/16

### ISSUE THREAD

**Issue by WhiteSpin** [knub/onehundredandeighty#26]
Nach meinen Informationen wird Computer-Grafik 1 im WS2015/16 angeboten und dafür im SS2016 nicht.

**Comment by knub** [comment]
Jap, das wird gefixt, sobald die Daten fuer das naechste Semester eingepflegt sind. Solange es keine Daten gibt, versucht 180 einfach zu extrapolieren und nimmt an, das Veranstaltungen im jeweils naechsten Sommer-/Wintersemester wieder angeboten werden.

Wenn du schon gern planen willst, kannst du CG1 fuer das naechste Semester in die data.js eintragen und einen PR stellen.

**Comment by knub** [comment]
Should be fixed by now.
