### ISSUE TITLE
final grade calculation

### ISSUE THREAD

**Issue by Nef10** [knub/onehundredandeighty#30]
It would be nice to have a calculation for the optimal final grade

**Comment by knub** [comment]
I agree. However, I do not have plans for implementing that.
It requires a lot of work, and you have to be very careful to not make errors (i.e. build a collection of real world examples).
But in case you want, feel free to start, I'd be happy to assist.

Also see: https://github.com/tessi/hpi_planer

**Comment by knub** [comment]
Closing as won't fix.
